[package]
name = "connect-sdk"
description = "An SDK for interacting with Skip:Connect"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/skip-mev/connect-sdk"
homepage = "https://skip.build"

[dependencies]
cosmwasm-std = { version="2.1.3", features = [ ] }
serde = { version = "1.0.207", default-features = false, features = ["derive"] }
schemars = "0.8.21"
serde-cw-value = "0.7.0"
protobuf = "3.5"
serde_json = "1.0.124"
prost = "0.13"
prost-types = "0.13"
tendermint-proto = "0.39"

[dev-dependencies]
prost-types = "0.13"

[features]
stargate = ["cosmwasm-std/stargate"]
